### ISSUE TITLE
 invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vdovaT** [stratosnet/stratos-chain#114]
![image](https://user-images.githubusercontent.com/84059393/154427763-e47486f5-6500-4293-bcbe-15edf526fb1a.png)

**Comment by alexstratos** [comment]
two possible reason, 
1. you the binary can't find a genesis with proper value at the /data/stratos/config/genesis.json.  in this case, you need to get the right genesis file.
2. your node started before with wrong genesis, in this case, you need to clean sub folders under /data/stratos/data folder and restart gain

**Comment by hong-pang** [comment]
since no more comments for several day, we will close this issue.
